routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('reset_password/{token}', ['as' => 'password.reset', function ($token) {
// implement your reset password route here!
// }]);

// Route::get('/', function () {
//     return view('home', ['title' => 'Home']);
// });

Auth::routes();

Route::resource('partner', 'PartnerController');
Route::resource('restaurant', 'RestaurantController');

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('/partner/new', 'PartnerController@create')->middleware('auth');
// Route::get('/partner', 'PartnerController@index');
Route::get('/event', 'HomeController@showEvent');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');

// Route::post('/partner/new', 'PartnerController@create')->middleware('auth');

app/Http/Controllers/Partner/Controller.php
<?php

namespace App\Http\Controllers\Partner;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Partner/GaleryController.php
<?php

namespace App\Http\Controllers;

use App\Model\tbl_person_galery;
use Illuminate\Http\Request;

class GaleryController extends Controller
{
    /**
     * Create a new AuthController instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:api', []);
    }

    //
    public function index(Request $request)
    {
        $params = $request->route('id');
        $results = tbl_regions::where('id', $params)->first();
        if (!$results) {
            throw new NotFoundHttpException();
        }
        return response()->json([
            'status' => true,
            'params' => $params,
            'result' => $results,
        ], 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        return tbl_regions::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show(Request $request)
    {
        // Query Builder
        $country_id = $request->get('country_id');
        $region_name = $request->get('name');
        $country_name = tbl_countries::where('id', $country_id)->pluck('name')->toArray();

        $results = tbl_regions::where([
            ['country_id', '=', $country_id],
            ['name', 'like', '%' . $region_name . '%'],
            ['code', 'like', '%' . $region_name . '%', 'or'],
        ])->paginate($request->get('pageSize') ?? 10)->toArray();

        // Check results
        if (!$results || !$country_id) {
            throw new NotFoundHttpException();
        }

        // Return Response
        return response()->json([
            'status' => 'ok',
            'success' => true,
            'country_name' => implode($country_name),
            'page' => $results['current_page'],
            'last' => $results['last_page'],
            'pageSize' => $results['per_page'],
            'total' => $results['total'],
            'data' => $results['data'],
        ], 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $results = tbl_regions::findOrFail($id);
        $results->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $results = tbl_regions::findOrFail($id);
        $results->delete();

        return 204;
    }
}

app/Http/Controllers/Partner/OutletController.php
<?php

namespace App\Http\Controllers\Partner;


use Auth;
use App\Model\Partner\tbl_partner_person;
use App\Model\Partner\tbl_partner_restaurant;
use App\Model\Partner\tbl_partner_outlet;
use App\Http\Requests\Partner\OutletRequest;
use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class OutletController extends Controller
{
    /**
     * Create a new AuthController instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:api', ['except' => ['show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $params = $request->route('id');
        $results = tbl_partner_outlet::where('id', $params)->first();
        if(!$results) {
            throw new NotFoundHttpException();
        }
        return response()->json([
            'status' => true,
            'params' => $params,
            'result' => $results
        ], 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(OutletRequest $request)
    {
        // id user yg sedang login
        $auth_id = Auth::guard()->user()['id'];
        
        // check validasi input
        $data = new tbl_partner_outlet($request->all());
        $count = tbl_partner_outlet::
                                where('restaurant_id', '=', $request->get('restaurant_id'))
                                ->where('deleted', '=', 0)
                                ->count();
        if ($count >= 5) {
            return response()->json([
                'status' => 'failed',
                'ok' => false,
                'count' => $count,
                'message' => 'You already have outlet data',
            ], 422);
        }
        $person = tbl_partner_person::
        where('user_id', '=', $auth_id)
        // ->where('created_by', '=', $auth_id, 'or')
        ->pluck('id')
        ->toArray();
        if (empty($person)) {
            return response()->json([
                'status' => 'failed',
                'ok' => false,
                'message' => 'You do not have personal data',
            ], 422);
        }
        $data['created_by'] = $auth_id;
        $authorize_edit = tbl_partner_restaurant::
                                where('id', '=', $request->get('restaurant_id'))
                                ->where('deleted', '=', 0)
                                ->count() || 0;
        if ($authorize_edit = 0) {
            return response()->json([
                'status' => 'failed',
                'ok' => false,
                'message' => 'You do not have restaurant',
            ], 422);
        }

        // Jika Failed
        if(!$data->save()) {
            throw new NotFoundHttpException();
        }

        // Jika Success
        return response()->json([
            'status' => 'ok',
            'ok' => true,
            'data' => $data
        ], 201);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $q = $request->get('q');
        $type = $request->get('type') ?? 'or';
        $strict = $request->get('strict') ?? 'true';
        $condition = [];

        if ($strict === 'true' || $strict === '1' || $strict) {
            foreach ($q as $key => $value) {
                array_push($condition, [$key, '=', $q[$key], $type]);
            }
        }
        if ($strict === 'false' || $strict === '0' || !$strict) {
            foreach ($q as $key => $value) {
                array_push($condition, [$key, 'LIKE', '%' . $q[$key] . '%', $type]);
            }
        }
        
        $results = tbl_partner_outlet::
        where(
            $condition
        )
        ->where('deleted', '=', 0)
        ->paginate(10)->toArray();
        
        // Check results
        if(!$results) {
            throw new NotFoundHttpException();
        }

        // Return Response
        return response()->json([
            'status' => 'ok',
            'success'=>true,
            'page' => $results['current_page'],
            'pageSize' => $results['per_page'],
            'last' => $results['last_page'],
            'total' => $results['total'],
            'data' => $results['data']
        ], 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(tbl_partner_outlet $data, OutletRequest $request)
    {
        // id user yg sedang login
        $auth_id = Auth::guard()->user()['id'];
        
        // check validasi input
        $user = new tbl_partner_outlet($request->all());
        $user['updated_by'] = $auth_id;
        $params = $request->route('id');

        $authorize_edit = tbl_partner_person::
                                where('user_id', '=', $params)
                                ->where('created_by', '=', $params, 'or')
                                ->where('deleted', '=', 0)
                                ->pluck('id')
                                ->toArray();
        $count = tbl_partner_outlet::
                                where('id', '=', $params)
                                ->where('restaurant_id', '=', implode($authorize_edit))
                                ->where('deleted', '=', 0)
                                ->count();
        if (empty($authorize_edit)) {
            return response()->json([
                'status' => 'failed',
                'ok' => false,
                'count' => $count,
                'message' => 'Restaurant Data Not Found',
            ], 422);
        }
        if ($count < 1) {
            return response()->json([
                'status' => 'failed',
                'ok' => false,
                'count' => $count,
                'message' => 'Restaurant Data Not Found',
            ], 422);
        }
        $results = $data::
        where('deleted', '=', 0)
        ->findOrFail($params);
        $results->touch();
        $results->update($request->except(['restaurant_id']));
        
        if (!$results) {
            throw new NotFoundHttpException();
        }

        return response()->json([
            'status' => 'ok',
            'ok' => true,
            'data' => $results
        ], 201);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Partner/PersonController.php
<?php

namespace App\Http\Controllers\Partner;

use App\Http\Requests\Partner\PersonRequest;
use App\Model\Partner\tbl_partner_person;
use Auth;
use DB;
use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class PersonController extends Controller
{
    /**
     * Create a new AuthController instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:api', []);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $params = $request->route('id');
        $auth_id = Auth::guard()->user()['id'];
        $results = tbl_partner_person::where('user_id', $auth_id)
            ->first();
        if (!$results) {
            throw new NotFoundHttpException();
        }
        return response()->json([
            'status' => 'ok',
            'ok' => true,
            'data' => $results,
        ], 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(PersonRequest $request)
    {
        // id user yg sedang login
        $auth_id = Auth::guard()->user()['id'];

        // check validasi input
        $user = new tbl_partner_person($request->all());

        // custom column yg tidak diinput
        $user['created_by'] = $auth_id;
        $user['user_id'] = $auth_id;

        $count = DB::table('tbl_partner_person')
            ->where('created_by', '=', $auth_id)
            ->where('deleted', '=', 0)
            ->count();

        // Check jika sudah ada data personal
        if ($count >= 1) {
            return response()->json([
                'status' => 'failed',
                'ok' => false,
                'count' => $count,
                'message' => 'You already have personal data',
            ], 422);
        }
        // Jika Failed
        if (!$user->save()) {
            throw new NotFoundHttpException();
        }

        // Jika Success
        return response()->json([
            'status' => 'ok',
            'ok' => true,
            'data' => tbl_partner_person::
                where([
                ['user_id', $auth_id],
            ])
                ->where('deleted', '=', 0)
                ->first(),
        ], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        // Query Builder
        $person_name = $request->get('name') ?? '';

        $results = tbl_partner_person::
            where([
            ['name', 'like', '%' . $person_name . '%', 'or'],
        ])
            ->where('deleted', '=', 0)
        // ->limit(1)->get();
            ->paginate(2)->toArray();

        // Check results
        if (!$results) {
            throw new NotFoundHttpException();
        }

        // Return Response
        return response()->json([
            'status' => 'ok',
            'success' => true,
            'page' => $results['current_page'],
            'pageSize' => $results['per_page'],
            'last' => $results['last_page'],
            'total' => $results['total'],
            'data' => $results['data'],
            // 'data' => $results
        ], 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(tbl_partner_person $person, PersonRequest $request)
    {
        // id user yg sedang login
        $user_id = Auth::guard()->user()['id'];

        // check validasi input
        $user = new tbl_partner_person($request->all());
        $user['updated_by'] = $user_id;
        $params = $request->route('id');
        $count = DB::table('tbl_partner_person')
            ->where('user_id', '=', $user_id)
            ->where('deleted', '=', 0)
            ->count();
        if ($count < 1) {
            return response()->json([
                'status' => 'failed',
                'ok' => false,
                'count' => $count,
                'message' => 'Personal Data Not Found',
            ], 422);
        }
        $results = tbl_partner_person::where('user_id', '=', $user_id)
            ->where('deleted', '=', 0)
            ->first();
        $results->touch();
        $results->update($request->except(['user_id']));
        if (!$results) {
            throw new NotFoundHttpException();
        }
        return response()->json([
            'status' => 'ok',
            'ok' => true,
            'data' => $results,
        ], 201);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * approve the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function approve(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/app/partner/create.blade.php
@extends('layouts.app') @section('title', 'Partner') @section('assets')
<link href="{{ asset('css/partner.css') }}" rel="stylesheet">
<link href="{{ asset('css/auth.css') }}" rel="stylesheet"> @endsection @section('content')
<div class="ui container">
    <div class="ui two centered stackable column grid">
        <div class="two wide">
            @if (isset($message['status']))
            <div class="ui message">
                <i class="close icon"></i>
                <p>{{ $message['status'] }}</p>
            </div>
            @endif
            <div class="ui loginform form">
                <div class="ui dividing header">
                    {{ __('Register Partner') }}
                </div>
                <div class="ui form">
                    <form method="POST" action="{{ route('partner.store') }}" accept-charset="UTF-8">
                        {{ csrf_field() }}
                        <!-- <div class="form-group inline field row">
                            <label for="name" class="col-sm-4 col-form-label text-md-right">{{ __('Nama') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}"
                                    required autofocus>
                            </div>
                        </div>
                        @if (isset($message['name']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['name']) }}</strong>
                        </span>
                        @endif -->

                        <!-- <div class="form-group inline field row">
                            <label for="email" class="col-sm-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="email" type="text" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}"
                                    required>
                            </div>
                        </div>
                        @if (isset($message['email']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['email']) }}</strong>
                        </span>
                        @endif -->

                        <div class="form-group inline field row">
                            <label for="address01" class="col-sm-4 col-form-label text-md-right">{{ __('Alamat') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="address01" type="text" class="form-control{{ $errors->has('address01') ? ' is-invalid' : '' }}" name="address01"
                                    value="{{ old('address01') }}" required>
                            </div>
                        </div>
                        @if (isset($message['address01']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['address01']) }}</strong>
                        </span>
                        @endif


                        <div class="form-group inline field row">
                            <label for="taxNo" class="col-sm-4 col-form-label text-md-right">{{ __('NPWP') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="taxNo" type="text" class="form-control{{ $errors->has('taxNo') ? ' is-invalid' : '' }}" name="taxNo" value="{{ old('taxNo') }}"
                                    required>
                            </div>
                        </div>
                        @if (isset($message['taxNo']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['taxNo']) }}</strong>
                        </span>
                        @endif

                        <div class="form-group inline field row">
                            <label for="phone" class="col-sm-4 col-form-label text-md-right">{{ __('No Telp') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="phone" type="tel" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" value="{{ old('phone') }}"
                                    required>
                            </div>
                        </div>
                        @if (isset($message['phone']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['phone']) }}</strong>
                        </span>
                        @endif

                        <div class="form-group inline field row">
                            <label for="whatsapp" class="col-sm-4 col-form-label text-md-right">{{ __('Whatsapp') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="whatsapp" type="tel" class="form-control{{ $errors->has('whatsapp') ? ' is-invalid' : '' }}" name="whatsapp" value="{{ old('whatsapp') }}"
                                    required>
                            </div>
                        </div>
                        @if (isset($message['whatsapp']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['whatsapp']) }}</strong>
                        </span>
                        @endif

                        <div class="form-group inline field row">
                            <label for="line" class="col-sm-4 col-form-label text-md-right">{{ __('Line') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="line" type="text" class="form-control{{ $errors->has('line') ? ' is-invalid' : '' }}" name="line" value="{{ old('line') }}"
                                    required>
                            </div>
                        </div>
                        @if (isset($message['line']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['line']) }}</strong>
                        </span>
                        @endif

                        <div class="form-group inline field row">
                            <label for="telegram" class="col-sm-4 col-form-label text-md-right">{{ __('Telegram') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="telegram" type="text" class="form-control{{ $errors->has('telegram') ? ' is-invalid' : '' }}" name="telegram"
                                    value="{{ old('telegram') }}" required>
                            </div>
                        </div>
                        @if (isset($message['telegram']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['telegram']) }}</strong>
                        </span>
                        @endif

                        <div class="form-group inline field row">
                            <label for="contact1" class="col-sm-4 col-form-label text-md-right">{{ __('Other contact') }}</label>

                            <div class="col-md-6 ui input">
                                <input id="contact1" type="text" class="form-control{{ $errors->has('contact1') ? ' is-invalid' : '' }}" name="contact1"
                                    value="{{ old('contact1') }}" required>
                            </div>
                        </div>
                        @if (isset($message['contact1']))
                        <span class="invalid-feedback">
                            <strong>{{ implode(" ", $message['contact1']) }}</strong>
                        </span>
                        @endif
                        <div class="field">
                            <button type="text" class="ui button primary  btn btn-primary">
                                {{ __('Submit') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection @section('js')
<script type="text/javascript">
    $('.message .close')
        .on('click', function () {
            $(this)
                .closest('.message')
                .transition('fade')
                ;
        })
        ;
</script> @endsection

resources/views/app/partner/index.blade.php
@extends('layouts.app') @section('title', 'Partner') @section('assets')
<link href="{{ asset('css/partner.css') }}" rel="stylesheet"> @endsection @section('content') @if (session('status'))
<div class="ui message">
    <i class="close icon"></i>
    <p>{{ session('status') }}</p>
</div>
@endif @if (session('warning'))
<div class="ui message">
    <i class="close icon"></i>
    <p>{{ session('warning') }}</p>
</div>
@endif
<div class="ui container">
    <div class="ui two stackable column grid">
        <div class="two wide">
            <a id="newPartner" href="{{ route('partner.create') }}">
                <button class="ui labeled icon button primary">
                    <i class="{{isset($message['usageIcon']) ? $message['usageIcon'] : 'plus'}} icon"></i>
                    {{ isset($message['usage']) ? $message['usage'] : 'Join' }}
                </button>
            </a>
            <a id="newPartner" href="{{ url('/restaurant') }}">
                <button class="ui labeled icon green button">
                    <i class="food icon"></i>
                    Restaurant
                </button>
            </a>
        </div>
    </div>
    <div class="ui stackable four column grid">
        @foreach($restaurant as $item)
        <div class="column">

            <div class="ui card">
                <div class="image">
                    <img src="{{ asset('images/diet-food-fresh-247685.jpg') }}">
                </div>
                <div class="content">
                    <a class="header">
                        {{ json_encode($item['name']) }}
                    </a>
                    <div class="meta">
                        <span class="date">
                            {{ json_encode($item['address01']) }}
                        </span>
                    </div>
                    <div class="description">
                        {{ json_encode($item['address02']) }}
                    </div>
                </div>
                <div class="extra content">
                    <a>
                        <i class="user icon"></i>
                    </a>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection